name: build-release

on: [push]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: on
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
 
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
         path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
 
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - run: pwd
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
          workdir: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}